spring:
  application:
    name: HotelService

  datasource:
    .url: jdbc:postgresql://localhost:5432/hotel-service
    .username: postgres
    .password: password

  jpa:
    .hibernate:
      ddl-auto: update
    .show-sql: true

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

